server:
  port: 8083

spring:
  application:
    name: wallet-manager-service
  config:
    import: configserver:http://localhost:8071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

