server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person-service
    username: student
    password: student

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/