server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet-service
    username: student
    password: student

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/